/**
 * envpact-action entry point.
 *
 * Fetches the vault repo via the GitHub Contents API (no git clone
 * needed), resolves secrets for the current repo, writes .env, and
 * optionally syncs to GitHub Actions repo secrets.
 */

import * as coreDefault from '@actions/core';
import * as fsDefault from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveProject, ENC_PREFIX } from './resolver.js';

function parseEnvExample(fs, filePath) {
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, 'utf8');
  const keys = [];
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && !keys.includes(key)) keys.push(key);
  }
  return keys;
}

function needsQuoting(v) {
  if (v === '') return true;
  if (/[\s#"'\\]/.test(v)) return true;
  if (/^\s/.test(v) || /\s$/.test(v)) return true;
  if (v.includes('\n') || v.includes('\r')) return true;
  return false;
}

function escape(v) {
  return v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
}

function formatValue(v) {
  v = String(v);
  return needsQuoting(v) ? `"${escape(v)}"` : v;
}

/**
 * Build the .env file body from an ordered key list and a resolved map.
 * Pure helper; exported for tests.
 */
export function buildEnvFile(orderedKeys, resolved, meta = {}) {
  const lines = [
    `# Generated by envpact-action on ${meta.timestamp || new Date().toISOString()}`,
    '# DO NOT COMMIT',
    `# project: ${meta.projectName ?? ''}`,
    `# environment: ${meta.environment ?? ''}`,
    '',
  ];
  for (const k of orderedKeys) {
    if (k in resolved) lines.push(`${k}=${formatValue(resolved[k])}`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Mask every non-empty value via the supplied setSecret callback.
 * Pure helper; exported for tests.
 */
export function maskAll(values, setSecretFn) {
  for (const v of values) {
    if (typeof v === 'string' && v.length > 0) setSecretFn(v);
  }
}

export async function fetchVault(repoSlug, token) {
  const url = `https://api.github.com/repos/${repoSlug}/contents/secrets.json`;
  const res = await fetch(url, {
    headers: {
      Authorization: `token ${token}`,
      Accept: 'application/vnd.github.raw',
      'User-Agent': 'envpact-action',
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(
      `Failed to fetch vault from ${repoSlug}: ${res.status} ${res.statusText}\n${body}`
    );
  }
  return JSON.parse(await res.text());
}

function autoDetectProject() {
  const repo = process.env.GITHUB_REPOSITORY;
  if (!repo) return path.basename(process.cwd()).toLowerCase();
  const m = repo.match(/^[^/]+\/(.+)$/);
  return (m ? m[1] : repo).toLowerCase();
}

export async function setRepoSecret(repoSlug, key, value, adminToken) {
  // GitHub requires libsodium-sealed boxes for repo secrets.
  // Rather than embed sodium, we shell out to `gh secret set` which
  // is always present on GitHub-hosted runners.
  const { exec } = await import('@actions/exec');
  await exec('gh', ['secret', 'set', key, '--body', value, '--repo', repoSlug], {
    env: { ...process.env, GH_TOKEN: adminToken },
  });
}

/**
 * Action runner. Dependencies are injected so that tests can swap
 * out @actions/core, fs, the vault fetcher, and the secret-syncer
 * without monkey-patching modules. Production callers can omit deps
 * and the sensible defaults below kick in.
 */
export async function run(deps = {}) {
  const core = deps.core || coreDefault;
  const fs = deps.fs || fsDefault;
  const fetchVaultFn = deps.fetchVault || fetchVault;
  const setRepoSecretFn = deps.setRepoSecret || setRepoSecret;

  try {
    const vaultRepo = core.getInput('vault-repo', { required: true });
    const vaultToken = core.getInput('vault-token', { required: true });
    let projectName = core.getInput('project-name');
    const environment = core.getInput('environment') || undefined;
    const outputFile = core.getInput('output-file') || '.env';
    const envExample = core.getInput('env-example') || '.env.example';
    const exportToEnv = core.getInput('export-to-env') === 'true';
    const syncGithubSecrets = core.getInput('sync-github-secrets') === 'true';

    if (!projectName) projectName = autoDetectProject();
    projectName = projectName.toLowerCase();

    core.info(`envpact-action: resolving project=${projectName} env=${environment || 'default'} from ${vaultRepo}`);

    const vault = await fetchVaultFn(vaultRepo, vaultToken);
    const result = resolveProject(vault, projectName, environment);

    if (result.missing) {
      core.warning(
        `Project "${projectName}" not found in vault. .env will be empty unless .env.example provides keys.`
      );
    }

    // AUDIT #6: Refuse to materialize encrypted values. The action runtime
    // does not carry decryption keys, so an enc:* value would be written to
    // .env / exported / synced verbatim — silently breaking downstream
    // consumers. Detect via the resolver's `encrypted` list AND via a
    // defensive re-scan of resolved values, then fail BEFORE any side
    // effects (writeFileSync / exportVariable / sync-github-secrets).
    const encryptedKeys = new Set(result.encrypted || []);
    for (const [k, v] of Object.entries(result.resolved)) {
      if (typeof v === 'string' && v.startsWith(ENC_PREFIX)) encryptedKeys.add(k);
    }
    if (encryptedKeys.size > 0) {
      const list = [...encryptedKeys].sort().join(', ');
      core.setFailed(
        `Encrypted values cannot be materialized by envpact-action: ${list}. ` +
          `Decrypt them with envpact-cli (e.g. \`envpact decrypt\`) before publishing the vault, ` +
          `or remove the enc:* prefix.`
      );
      return;
    }

    const requiredKeys = parseEnvExample(fs, envExample);
    const orderedKeys = requiredKeys.length ? requiredKeys : Object.keys(result.resolved);

    // CRITICAL: register every resolved value as a secret BEFORE
    // any logging, file write, or `cat .env` opportunity. Once
    // core.setSecret is called, the GitHub Actions runner masks
    // the value in all subsequent log output for the rest of the
    // job — but only from the point of registration onward.
    //
    // ORDERING INVARIANT: every core.setSecret(...) call below MUST
    // execute before the first fs.writeFileSync below. Do not
    // reorder. Tests in tests/index.test.js assert this index-wise.
    maskAll(Object.values(result.resolved), (v) => core.setSecret(v));

    const body = buildEnvFile(orderedKeys, result.resolved, {
      projectName,
      environment: result.environment,
    });

    fs.writeFileSync(outputFile, body, { encoding: 'utf8', mode: 0o600 });
    core.info(`✓ Wrote ${Object.keys(result.resolved).length} keys to ${outputFile}`);

    if (exportToEnv) {
      for (const [k, v] of Object.entries(result.resolved)) {
        core.exportVariable(k, v);
      }
    }

    if (result.unresolved.length) {
      core.warning(`Unresolved keys: ${result.unresolved.join(', ')}`);
    }

    if (syncGithubSecrets) {
      const adminToken = process.env.GH_ADMIN_TOKEN || vaultToken;
      const targetRepo = process.env.GITHUB_REPOSITORY;
      if (!targetRepo) throw new Error('GITHUB_REPOSITORY env var not set');
      let synced = 0;
      for (const [k, v] of Object.entries(result.resolved)) {
        try {
          await setRepoSecretFn(targetRepo, k, v, adminToken);
          synced++;
        } catch (e) {
          core.warning(`Could not set secret ${k}: ${e.message}`);
        }
      }
      core.info(`✓ Synced ${synced}/${Object.keys(result.resolved).length} secrets to ${targetRepo}`);
    }

    core.setOutput('resolved-count', Object.keys(result.resolved).length);
    core.setOutput('env-file-path', outputFile);
    core.setOutput('unresolved-keys', result.unresolved.join(','));
  } catch (e) {
    core.setFailed(e.message);
  }
}

// Only fire the action when this module is executed directly (e.g. via
// `node src/index.js` or the bundled dist/index.js entry). When imported
// from tests, the bottom-of-module side effect must not run.
const isMain = (() => {
  try {
    if (!process.argv[1]) return false;
    return fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
  } catch {
    return false;
  }
})();

if (isMain) {
  run();
}
