/**
 * envpact-action entry point.
 *
 * Fetches the vault repo via the GitHub Contents API (no git clone
 * needed), resolves secrets for the current repo, writes .env, and
 * optionally syncs to GitHub Actions repo secrets.
 */

import * as core from '@actions/core';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { resolveProject } from './resolver.js';

function parseEnvExample(filePath) {
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, 'utf8');
  const keys = [];
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && !keys.includes(key)) keys.push(key);
  }
  return keys;
}

function needsQuoting(v) {
  if (v === '') return true;
  if (/[\s#"'\\]/.test(v)) return true;
  if (/^\s/.test(v) || /\s$/.test(v)) return true;
  if (v.includes('\n') || v.includes('\r')) return true;
  return false;
}

function escape(v) {
  return v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
}

function formatValue(v) {
  v = String(v);
  return needsQuoting(v) ? `"${escape(v)}"` : v;
}

async function fetchVault(repoSlug, token) {
  const url = `https://api.github.com/repos/${repoSlug}/contents/secrets.json`;
  const res = await fetch(url, {
    headers: {
      Authorization: `token ${token}`,
      Accept: 'application/vnd.github.raw',
      'User-Agent': 'envpact-action',
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(
      `Failed to fetch vault from ${repoSlug}: ${res.status} ${res.statusText}\n${body}`
    );
  }
  return JSON.parse(await res.text());
}

function autoDetectProject() {
  const repo = process.env.GITHUB_REPOSITORY;
  if (!repo) return path.basename(process.cwd()).toLowerCase();
  const m = repo.match(/^[^/]+\/(.+)$/);
  return (m ? m[1] : repo).toLowerCase();
}

async function setRepoSecret(repoSlug, key, value, adminToken) {
  // GitHub requires libsodium-sealed boxes for repo secrets.
  // Rather than embed sodium, we shell out to `gh secret set` which
  // is always present on GitHub-hosted runners.
  const { exec } = await import('@actions/exec');
  await exec('gh', ['secret', 'set', key, '--body', value, '--repo', repoSlug], {
    env: { ...process.env, GH_TOKEN: adminToken },
  });
}

async function run() {
  try {
    const vaultRepo = core.getInput('vault-repo', { required: true });
    const vaultToken = core.getInput('vault-token', { required: true });
    let projectName = core.getInput('project-name');
    const environment = core.getInput('environment') || undefined;
    const outputFile = core.getInput('output-file') || '.env';
    const envExample = core.getInput('env-example') || '.env.example';
    const exportToEnv = core.getInput('export-to-env') === 'true';
    const syncGithubSecrets = core.getInput('sync-github-secrets') === 'true';

    if (!projectName) projectName = autoDetectProject();
    projectName = projectName.toLowerCase();

    core.info(`envpact-action: resolving project=${projectName} env=${environment || 'default'} from ${vaultRepo}`);

    const vault = await fetchVault(vaultRepo, vaultToken);
    const result = resolveProject(vault, projectName, environment);

    if (result.missing) {
      core.warning(
        `Project "${projectName}" not found in vault. .env will be empty unless .env.example provides keys.`
      );
    }

    const requiredKeys = parseEnvExample(envExample);
    const orderedKeys = requiredKeys.length ? requiredKeys : Object.keys(result.resolved);

    const lines = [
      `# Generated by envpact-action on ${new Date().toISOString()}`,
      '# DO NOT COMMIT',
      `# project: ${projectName}`,
      `# environment: ${result.environment}`,
      '',
    ];
    for (const k of orderedKeys) {
      if (k in result.resolved) lines.push(`${k}=${formatValue(result.resolved[k])}`);
    }

    fs.writeFileSync(outputFile, lines.join('\n') + '\n', { encoding: 'utf8', mode: 0o600 });
    core.info(`✓ Wrote ${Object.keys(result.resolved).length} keys to ${outputFile}`);

    // Mask all resolved values in logs
    for (const v of Object.values(result.resolved)) {
      if (v && v.length > 0) core.setSecret(v);
    }

    if (exportToEnv) {
      for (const [k, v] of Object.entries(result.resolved)) {
        core.exportVariable(k, v);
      }
    }

    if (result.unresolved.length) {
      core.warning(`Unresolved keys: ${result.unresolved.join(', ')}`);
    }

    if (syncGithubSecrets) {
      const adminToken = process.env.GH_ADMIN_TOKEN || vaultToken;
      const targetRepo = process.env.GITHUB_REPOSITORY;
      if (!targetRepo) throw new Error('GITHUB_REPOSITORY env var not set');
      let synced = 0;
      for (const [k, v] of Object.entries(result.resolved)) {
        try {
          await setRepoSecret(targetRepo, k, v, adminToken);
          synced++;
        } catch (e) {
          core.warning(`Could not set secret ${k}: ${e.message}`);
        }
      }
      core.info(`✓ Synced ${synced}/${Object.keys(result.resolved).length} secrets to ${targetRepo}`);
    }

    core.setOutput('resolved-count', Object.keys(result.resolved).length);
    core.setOutput('env-file-path', outputFile);
    core.setOutput('unresolved-keys', result.unresolved.join(','));
  } catch (e) {
    core.setFailed(e.message);
  }
}

run();
